# Generated by Django 2.0.6 on 2018-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0003_auto_20180815_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesi',
            name='TarikhKemaskini',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='TarikhKemaskini'),
        ),
    ]
