# Generated by Django 2.0.6 on 2018-08-15 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0004_auto_20180815_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesi',
            name='TarikhKemaskini',
            field=models.DateTimeField(max_length=60, verbose_name='TarikhKemaskini'),
        ),
    ]
