# Generated by Django 2.0.6 on 2018-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0006_sesi_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesi',
            name='TarikhKemaskini',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='TarikhKemaskini'),
        ),
    ]
