# Generated by Django 2.0.6 on 2018-08-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0007_auto_20180815_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesi',
            name='TarikhKemaskini',
        ),
    ]
