# Generated by Django 2.0.6 on 2018-08-16 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0008_remove_sesi_tarikhkemaskini'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
