# Generated by Django 2.0.6 on 2018-08-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0009_auto_20180816_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadual',
            name='TarikhAudit',
        ),
    ]
