# Generated by Django 2.0.6 on 2018-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0010_remove_jadual_tarikhaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadual',
            name='Status',
            field=models.IntegerField(default=1, verbose_name='Status'),
        ),
    ]
