# Generated by Django 2.0.6 on 2018-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0011_auto_20180816_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesi',
            name='JumlahSkala',
            field=models.IntegerField(default=6, verbose_name='Skala'),
            preserve_default=False,
        ),
    ]
