# Generated by Django 2.0.6 on 2018-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahagian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUOrgChart', models.CharField(max_length=300, verbose_name='Nama Bahagian')),
            ],
        ),
    ]
