# Generated by Django 2.0.6 on 2018-07-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urusetia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zon',
            name='IDZon',
        ),
    ]
