# Generated by Django 2.0.6 on 2018-07-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahagian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUOrgChart', models.IntegerField(unique=True, verbose_name='BUOrgChart')),
                ('NamaBahagian', models.CharField(max_length=60, verbose_name='Nama Bahagian')),
            ],
        ),
        migrations.CreateModel(
            name='Peranan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICNum', models.IntegerField(unique=True, verbose_name='ICNum')),
                ('JenisCapaian', models.CharField(max_length=60, verbose_name='JenisCapaian')),
            ],
        ),
        migrations.CreateModel(
            name='Zon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaZon', models.CharField(max_length=12, verbose_name='NamaZon')),
                ('BUOrgChart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urusetia.Bahagian')),
            ],
        ),
    ]
