# Generated by Django 2.0.6 on 2018-07-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penilaian', '0002_auto_20180718_0842'),
        ('urusetia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peranan',
        ),
    ]
