# Generated by Django 2.0.6 on 2018-07-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urusetia', '0002_delete_peranan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zon',
            name='NamaZon',
            field=models.CharField(max_length=30, verbose_name='NamaZon'),
        ),
    ]
