# Generated by Django 2.0.6 on 2018-07-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urusetia', '0003_auto_20180726_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zon',
            old_name='BUOrgChart',
            new_name='Bahagian',
        ),
    ]
