# Generated by Django 2.0.6 on 2018-08-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0004_auto_20180802_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soalan',
            old_name='KodSubKomponen',
            new_name='SubKomponen',
        ),
    ]
