# Generated by Django 2.0.6 on 2018-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0005_auto_20180803_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soalan',
            name='Soalan',
            field=models.CharField(max_length=200, verbose_name='Soalan'),
        ),
    ]
