# Generated by Django 2.0.6 on 2018-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0006_auto_20180803_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soalan',
            name='Soalan',
            field=models.CharField(max_length=600, verbose_name='Soalan'),
        ),
    ]
