# Generated by Django 2.0.6 on 2018-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0007_auto_20180803_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jawapan',
            old_name='NoSoalan',
            new_name='Soalan',
        ),
        migrations.AddField(
            model_name='soalan',
            name='Status',
            field=models.IntegerField(default=1, verbose_name='Statussoalan'),
        ),
    ]
