# Generated by Django 2.0.6 on 2018-08-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0009_auto_20180803_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawapan',
            name='Pemberat',
        ),
        migrations.AddField(
            model_name='jawapan',
            name='Skala',
            field=models.IntegerField(default=0, verbose_name='Skala'),
        ),
        migrations.AddField(
            model_name='komponen',
            name='PemberatKomponen',
            field=models.IntegerField(default=0, verbose_name='PemberatKomponen'),
        ),
        migrations.AddField(
            model_name='subkomponen',
            name='PemberatSubKomponen',
            field=models.IntegerField(default=0, verbose_name='PemberatSubKomponen'),
        ),
    ]
