# Generated by Django 2.0.6 on 2018-08-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0010_auto_20180809_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawapan',
            name='TarikhKemaskini',
        ),
    ]
