# Generated by Django 2.0.6 on 2018-07-18 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penilaian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komen',
            name='ICNum',
        ),
        migrations.RemoveField(
            model_name='skor',
            name='ICNum',
        ),
        migrations.AddField(
            model_name='komen',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skor',
            name='penilai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jadual',
            name='NamaJuruAudit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
