# Generated by Django 2.0.6 on 2018-07-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jawapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoJawapan', models.CharField(max_length=10, unique=True, verbose_name='NoJawapan')),
                ('DeskripsiJawapan', models.CharField(max_length=200, verbose_name='DeskripsiJawapan')),
                ('Pemberat', models.IntegerField(verbose_name='Pemberat')),
                ('TarikhKemaskini', models.DateTimeField(max_length=60, verbose_name='TarikhKemaskini')),
            ],
        ),
        migrations.CreateModel(
            name='Komponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodKomponen', models.CharField(max_length=10, unique=True, verbose_name='KodKomponen')),
                ('NamaKomponen', models.CharField(max_length=60, verbose_name='NamaKomponen')),
            ],
        ),
        migrations.CreateModel(
            name='Soalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoSoalan', models.CharField(max_length=10, unique=True, verbose_name='NoSoalan')),
                ('Soalan', models.CharField(max_length=200, verbose_name='NamaSubKomponen')),
            ],
        ),
        migrations.CreateModel(
            name='SubKomponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodSubKomponen', models.CharField(max_length=10, unique=True, verbose_name='KodSubKomponen')),
                ('NamaSubKomponen', models.CharField(max_length=60, verbose_name='NamaSubKomponen')),
                ('KodKomponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persediaan.Komponen')),
            ],
        ),
        migrations.AddField(
            model_name='soalan',
            name='KodSubKomponen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persediaan.SubKomponen'),
        ),
        migrations.AddField(
            model_name='jawapan',
            name='NoSoalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persediaan.Soalan'),
        ),
    ]
