# Generated by Django 2.0.6 on 2018-08-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0002_komponen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subkomponen',
            name='Status',
            field=models.IntegerField(default=1, verbose_name='Statussub'),
        ),
    ]
