# Generated by Django 2.0.6 on 2018-08-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persediaan', '0003_subkomponen_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subkomponen',
            old_name='KodKomponen',
            new_name='Komponen',
        ),
    ]
